'''
Counting Point Mutations
https://rosalind.info/problems/hamm/
'''


def counting_point_mutations(a,b):
    '''
    this function finds the number or corresponding nucleotides between a and b
    that dont match
    '''
    indexer = 0
    hamming_count = 0
    while True:
        if indexer >= len(a):
            break
        elif a[indexer] == b[indexer]:
            indexer += 1
        else:
            hamming_count += 1
            indexer += 1
    return(hamming_count)

if __name__ == '__main__':
    s = '''
    GGAAGATGCCAACATGATCTTCCTAGTAGTTATTATTTCTATATTATCGACCAAGAATACATCCATCCTGCCGTTCCTACTACTGCAAATGGGAAGCTGCACCTACACTCGTGGAACTCTCGAACCTAATTAAGTGGTGTACCTCGGGCTATGGTATTTCCACTTGAGTTTCCTTCAGCTTCAGATCGTCTCAAATGAGGATCTGCCTGGGTTTGACCAAGCGTCATTTTGGGTCTTGCAGAAGGCACTCCGGTGTGTCATGGGCGGATGATAGTACGGTTAATCTGGGCGGACTGGCCAACGTTGGTATTATAATTACTACGAAACACCGACCACACTCGATTCCGATCATCTACAAAGGGGTTGTCATTTGGTAACTGTGCCATAGTTTCGCGGATGAGATGGGTATATTAACAATCTACTTCAACGAGGCTGATGACTGCTGTACAGGTTGTTACTCAACGCGATCAAAGGGGCTCTTCCGCCCCGTCTACCATACTTTAGCCCAACTGAGTATCGTTAACGGCTGTGTAACGACAACGCACCGAAACGCAAAGTCCACTTGTGTTGGATTATTAGTCCCTCAGATTCACGATACTGCGCTTCGTTTGCGAAGTGCATCAGTAAAATTTGATTATATCGTACATGGGGCACCTCCGTCGCAGATCGTGAAGAACCTCACTTAACTCCCGGGACCGCATCTCTGGGGCACGCGTGTATTGCTACCTACGCAAGCTTAACAATATGCTCATCCCCCCGAGGGTGGTGTAAACGATAGTATGCATACTCATTAGAGATAAGTTAGGCTGAAGTCAGTTAGCCTACCTGAGCTACAGTAGGACCCAAAAGAGCTCCATTTTGCGAGTCTGGTGAAGACCTCGTAATCTAGGGGAAGCAGGCGACCACCTATGGTAAT
    '''
    t = '''
    GATACCCAGAAGGCGTATCGTCCTGTTAGCCATTCTGGCTGTTTTACAGACTTAGTCGACTTCTAAAATGCAGCTACTACATTGGCTCATTGCCAGACGAAACAGCACCCATAGTATTACTGTCCCCGGTCAGTTAACATGCCTCGGATTAAGTTACGTTCCCGACGAGTTTCTTTCGCTTCTCAAGACATCCCAGTCTGCCAGGTCTGGTCGGGCGCGAGCGTCACAATTGGTCTTACGAGAGATACGTGCGTGTAAGATATGGGTACCTTTGTACGGTCAACGGGGCAAGAATATCCACCGGATCTCGCACATCACGGCCGGGTAACCAACTGAGCTGGAGTCCCACCTCGTGCCAAGGTGTTGTCATTTCACCTATTTGCCGTAGCTTCCCTAACGCGATGTCGACAGTGGTACCCTACTTTTTAGATGATCATACCGGTCCTCCTGTTTATAAGTTAAGGTTGACAGAGAACGACATCCGGCTCTTCTCCCTTAATCGCGGATCCGTGATTCTCGTACAATGGTGCATAATGACTATCTCCCGTAACGCCATATCGCCCAGTGTAGGAGGCACAGCTAATCAGGGTTTCCACGCGATGACTCAACATAGCCGTGCATGATCAAAATTTCAGCAAAGCGTCAAGTATTAACCAACGGTGCTCATGGTCAAGTTAATTACCAGACACAAGCGACACTATAGCGGAGCAATGCTTGTAATGATACGGGCTCAAGTTGGAAATGAAGCCAATGTGAGCTTAAACAAGATATCCCGTGTTACGCATACCGTGCCATGTGGTGGTGCCAAAAGTCGCGATGATAGCCCTCACTTACTGTAATGCTCAGAGGTACCTCTATACCAATAATCGGTGCTGTACTCGAGCTCACTGAAAAGTCTGAGCCCTCACGTTCTTAC
    '''
    ans = counting_point_mutations(s,t)
    print(ans)
