'''
Finding a Motif in DNA
https://rosalind.info/problems/subs/
'''

def finding_a_motif(motif,dna):
    '''
    This function takes a motif and a strand of dna and outputs all of the locations
    at which the motif is present
    '''
    dna_len = len(dna)
    counter = 0
    locations = ''
    while counter < dna_len - 3:
        if dna[counter:counter+len(motif)] == motif:
            locations = locations + str(counter + 1) + ' '
            counter+=1
        else:
            counter+=1
    return(locations)

if __name__ == '__main__':   
    dna = '''ATGACCGATGTGACCGACAAATGACCGATGACCGACCTGACCGAAGGTGACCGAAACAATGTTCTGACCGATGACCGATGTTATGACCGACATTTGACCGAAGTGACCGATGACCGAACACTGACCGATGACCGATGACCGATCCCCTATGACCGAATGACCGAGCTCGCTGACCGAATGACCGATTGACCGATGACCGAGTCCGCTTGCGTAAGCTGACCGAATGAGGATTGACCGAGGTGACCGATGACCGATTGACCGAGGTGACCGATTGACCGAGTGACCGAAATGATATTGACCGATGACCGATGACCGAGTGACCGATGACCGACTCGCCGGCTCTTTGACCGATTTTTGACCGATGACCGAGGATGACCGATGACCGACTGACCGAACGTGACCGAATGACCGAGATGACCGACCCGACTTGACCGACTGACCGATGACCGAGTGACCGATGACCGATGACCGACTACGCTGACCGAAGCTGACCGATATGACCGATGACCGAATGACCGATATACTTTGACCGATGACCGATTGACCGATGACCGAGTGACCGATGACCGATATGACCGAATGACCGATGTGACCGACTGACCGAAAACTCGGGAGAAGGACAGATCTAATCTGACCGAGATACCTGACCGACTGCAGAACTAGCATTGACCGATGACCGATGACCGATGGTGACCGAATGACCGATGACCGACTGACCGATGTGACCGACACCCATGACCGAGTCTATGACCGATGACCGAAACGATGGTCACTGTGACCGAGTGACCGATGACCGATGACCGACTGACCGA'''
    motif = 'TGACCGATG'
    ans = finding_a_motif(motif,dna)
    print(ans)
